In [1]:
#ベクトルの作成
#ライブラリをロード
import numpy as np
#行ベクトルを作成
vector_row = np.array([1,2,3])
#列ベクトルを作成
vector_column = np.array([
    [1],
    [2],
    [3]
])
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [2]:
#行列の作成
matrix = np.array([
    [1,2],
    [1,2],
    [1,2]
])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [3]:
#疎行列
#ライブラリをロード
import numpy as np
from scipy import sparse

matrix = np.array([
    [0,0],
    [0,1],
    [3,0]
])
#CSR(compressed sparse row)形式の行列を作る
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [4]:
#大きな行列を作成
matrix_large = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [3,0,0,0,0,0,0,0,0,0]
])
#CSR形式
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [5]:
#要素の選択
#ベクトルを作成
vector = np.array([1,2,3,4,5,6])

#行列を作成
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#3つ目の要素を選択
vector[2]

3

In [6]:
#2行目、2列目を選択
matrix[1,1]

5

In [7]:
#ベクトルのすべての要素を選択
vector[:]

array([1, 2, 3, 4, 5, 6])

In [8]:
#3番目までのすべての要素を選択。３番目を含む
vector[:3]

array([1, 2, 3])

In [9]:
#３番目より後のすべての要素を選択
vector[3:]

array([4, 5, 6])

In [10]:
#最後の要素を選択
vector[-1]

6

In [11]:
#行列から、最初の２つの行のすべての列を選択
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#すべての行の2列目を選択
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [13]:
#行列の性質
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
#行数、列数を表示
matrix.shape

(3, 4)

In [14]:
#要素数を表示
matrix.size

12

In [15]:
#次元数を表示
matrix.ndim

2

In [16]:
#要素に対する計算
#行列を作成
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#引数に100を加える関数を作成
add_100 = lambda i: i+100
#ベクトル化された関数を作成
vectorized_add_100 = np.vectorize(add_100)

#この関数をmatrixのすべての要素に適用
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [17]:
#すべての要素に100を加える
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [18]:
#行列から2つの行のすべての列を選択
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#最大値と最小値を見つける
#最大の要素を返す
np.max(matrix)

9

In [20]:
#最小の要素を返す
np.min(matrix)

1

In [21]:
#各列における最大要素を見つける
np.max(matrix,axis=0)

array([7, 8, 9])

In [22]:
#各行における最大要素を見つける
np.max(matrix,axis=1)

array([3, 6, 9])

In [23]:
#平均値、分散、標準偏差の計算
#平均値を算出
np.mean(matrix)

5.0

In [24]:
#分散を算出
np.var(matrix)

6.666666666666667

In [25]:
#標準偏差を算出
np.std(matrix)

2.581988897471611

In [26]:
#各列の平均値を算出
np.mean(matrix,axis=0)

array([4., 5., 6.])

In [27]:
#配列形状の変更
#4×3の行列を作成
Matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
#2×6の行列に形状変更
Matrix.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
Matrix.size

12

In [29]:
Matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [30]:
Matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
#ベクトル、行列の転置
#行列を転置
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
#ベクトルの転置
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [33]:
#行ベクトルの転置
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
#行列のフラット化
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#行列のランク/その行列で線形変換を行ったときに、空間が何次元になるのか
matrix = np.array([
    [1,1,1],
    [1,1,10],
    [1,1,15]
])
#行列のランクを返す
np.linalg.matrix_rank(matrix)

2

In [36]:
#行列式の計算/線型変換によって空間の体積要素が何倍に変わるかという概念を抽象化したもの

#行列を作成
matrix = np.array([
    [1,2,3],
    [2,4,6],
    [3,8,9]
])
#行列の行列式を算出
np.linalg.det(matrix)

0.0

In [37]:
#行列トレースの計算/対角要素の和
#トレースを返す
matrix.trace()

14

In [38]:
#固有値と固有ベクトル
matrix = np.array([
    [1,-1,3],
    [1,1,6],
    [3,8,9]
])
#固有値と固有ベクトルを計算
eigenvalues,eigenvectors = np.linalg.eig(matrix)

#固有値を表示
print(eigenvalues)
#固有ベクトルを表示
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [39]:
#内積の計算
#2つのベクトルを作成
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

#内積を計算
np.dot(vector_a,vector_b)

32

In [40]:
#内積を計算←これでもOK
vector_a @ vector_b

32

In [41]:
#行列の加算、減算
#行列を作成
matrix_a = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,2]
])
matrix_b = np.array([
    [1,3,1],
    [1,3,1],
    [1,3,8]
])
#２つの行列の加算
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [42]:
#2つの行列の減算
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [43]:
#2つの行列の加算その２
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [44]:
#行列の乗算
matrix_a = np.array([
    [1,1],
    [1,2]
])
matrix_b = np.array([
    [1,3],
    [1,2]
])
#2つの行列を乗算
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [45]:
#2つの行列を乗算
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [46]:
#要素ごとの計算
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [47]:
#逆行列の算出
matrix = np.array([
    [1,4],
    [2,5]
])
#逆行列を算出
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [48]:
#行列とその逆行列を乗算
matrix_1 = np.array([
    [-5/3,4/3],
    [2/3,-1/3]
])
print(matrix @ np.linalg.inv(matrix))#単位行列になるはずだが、ならない
print(matrix @ matrix_1)

np.linalg.inv(matrix) == matrix_1
-5/3

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00]
 [-3.33066907e-16  1.00000000e+00]]


-1.6666666666666667

In [49]:
#乱数の生成
#シード値を設定
np.random.seed(0)
#0,0と1.0の間のランダムな浮動小数点数値を３つ生成する
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [50]:
#1と10の間のランダムな整数値を3つ生成
np.random.randint(0,11,3)

array([3, 7, 9])

In [51]:
#平均0.0,標準偏差1.0の正規分布から3つの数値を生成する
np.random.normal(0.0,1.0,3)

array([-1.42232584,  1.52006949, -0.29139398])

In [52]:
#平均0.0,スケール1.0のロジスティック分布から３つの数値を生成
np.random.logistic(0.0,1.0,3)

array([-0.98118713, -0.08939902,  1.46416405])

In [53]:
#1.0以上で、2.0より小さい３つの数値を生成
np.random.uniform(1.0,2.0,3)

array([1.47997717, 1.3927848 , 1.83607876])

In [ ]:
import math
num=float(input("分数に直したい循環小数を入力してください:"))
num2=math.modf(num)
if num == num2[1]:
    num
else:
    keta=len(str(num))-2
    bunsi=float(num2[0])
    bunbo=float(str(9)*int(keta))
    print(bunsi+str("/")+bunbo)